---
en:
    errors:
        blank: must not be blank
        duplicate: has already been used
        format: is in an invalid format
        confirmation: must match its confirmation
        too_short: must be at least %{count} characters
        too_long: must be less than %{count} characters
    models:
        item:
            attrs:
                text: Item
    titles:
        sessions:
            new: Sign In
        users:
            new: Sign Up
